version: "3"

services:
# Reverse proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/proxy/custom_proxy.conf:/etc/nginx/conf.d/custom_proxy.conf:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "sittler.n@gmail.com"
    depends_on:
      - nginx-proxy

# ENVIRONNEMENT php
  php81:
    image: php:8.1-fpm
    container_name: php81
    volumes:
      - code:/var/www/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./names.csv:/var/www/project/public/names.csv

# APP Entry point
  nginx:
      image: marketplace_bonjour:latest
      container_name: marketplace-${SERVER_NAME}
      expose:
          - ${VIRTUAL_PORT}
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem
          - ./docker/nginx/snippets:/etc/nginx/snippets
          - ./docker/nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
          - ./docker/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
          - code:/var/www/project
          - ./names.csv:/var/www/project/public/names.csv
      links:
          - php81
      environment:
          VIRTUAL_HOST: ${VIRTUAL_HOST}
          VIRTUAL_PROTO: ${VIRTUAL_PROTO}
          VIRTUAL_PORT: ${VIRTUAL_PORT}
          LETSENCRYPT_HOST: ${VIRTUAL_HOST}
          LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

volumes:
  vhost:
  html:
  certs:
  acme:
  code:

networks:
  default:
      name: nginx-proxy