name: CI + CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  FunctionalTests:
    name: Functional tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
        node-version: ['18.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

  DeployBonjour:
    name: Deploy to Bonjour 
    if: github.event.ref == 'refs/heads/main'
    needs: [FunctionalTests]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'https://preprod.bonjour.alsace'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: baqmen/cicddocker:latest
          file: "{context}/docker/app/Dockerfile"

  
